import AppKit

/// Polls the general pasteboard's `changeCount` — there is no notification —
/// and hands new text to the store. Honors the pasteboard conventions password
/// managers use to mark secrets, and the app ignore list.
@MainActor
final class PasteboardWatcher {
    private let store: ClippingStore
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    /// Set by `Paster` so our own writes are not recorded as new copies.
    var changeCountToSkip: Int?

    private static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping")
    ]

    init(store: ClippingStore) {
        self.store = store
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        let timer = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        if let skip = changeCountToSkip, skip == count {
            changeCountToSkip = nil
            return
        }
        guard let types = pasteboard.types, Self.concealedTypes.isDisjoint(with: types) else { return }
        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        let source = NSWorkspace.shared.frontmostApplication
        if let bundleID = source?.bundleIdentifier, store.settings.ignoredBundleIDs.contains(bundleID) {
            return
        }
        store.add(text: text, sourceBundleID: source?.bundleIdentifier, sourceName: source?.localizedName)
    }
}
